vim.keymap.set('n', '<leader>s', ':source $MYVIMR<cr>', {})
-- select all
vim.keymap.set('n', '<leader>a', ':keepjumps normal! ggVG<cr>', {})
vim.keymap.set({'n', 'x'}, 'cp', '"+y', {})
vim.keymap.set({'n', 'x'}, 'cv', '"+p', {})
vim.keymap.set({'n', 'x', 'v'}, '<leader>l', ':set inrelativenumber<cr>', { noremap = true })
vim.keymap.set('n', '<Tab>', ':bnext<cr>', {})
vim.keymap.set('n', '<S-Tab>', ':bprevious<cr>', {})
vim.keymap.set('n', '<C-k>', ':wincmd k<cr>', {})
vim.keymap.set('n', '<C-j>', ':wincmd j<cr>', {})
vim.keymap.set('n', '<C-h>', ':wincmd h<cr>', {})
vim.keymap.set('n', '<C-l>', ':wincmd l<cr>', {})
vim.keymap.set('n', 'd[', vim.diagnostic.goto_prev)
vim.keymap.set('n', 'd]', vim.diagnostic.goto_next)
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float)
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist)
